### ISSUE TITLE
Controll from PR label

### ISSUE THREAD

**Issue by tenhobi** [K-Phoen/semver-release-action#22]
Hello, is it possible with this Action to control version incrementing using PR label, so I can release with major/minor/patch update to release's tag?

I need it to automate release deploying with version changes (https://github.com/tenhobi/bachelors-thesis/issues/8) 

e.g. :

- release v0.1.1
then PR w/ label "minor"
- release v0.2.0
then PR w/ label "major"
- release v1.0.0

// Original question from https://github.com/actions/create-release/issues/5#issuecomment-541518643

**Comment by K-Phoen** [comment]
That's precisely what this action does :)

It uses the PR label to tag and release the next version accordingly.

**Comment by tenhobi** [comment]
Oh, I must have misread or forgot to read the README. Wow, thanks, that will solve my problem! 👍 ❤️
