### ISSUE TITLE
Allow specifying a default semver version bump when no label is provided

### ISSUE THREAD

**Issue by cbrwizard** [K-Phoen/semver-release-action#26]
It would be cool to allow specifying a default semver version bump in case when no labels are provided in a PR.

Eg: `default_version`: `patch`, so that `patch` version gets bumped by default. If a user doesn't provide `default_version` then a label is required as before. If `default_version` is provided, but a pr has a different version label eg `minor`, then a pr's label gets priority.

**Comment by K-Phoen** [comment]
Hi!

Thanks for opening this issue :)

As the main goal of this action is to bump the version only when a label is provided, I'm currently not in favor of introducing such feature. That being said, I'll leave this issue open to see if more people request it, and if so, I'll consider it.

**Comment by lucaskjaero** [comment]
Hi! I also would like this feature.

**Comment by elliotjberman** [comment]
+1

**Comment by joe-bowman** [comment]
+1

**Comment by acidjazz** [comment]
+1

**Comment by stormmore** [comment]
+1

It would be preferable to only to have to label the next minor or next major version and just assume if no label means patch

**Comment by krogon** [comment]
@K-Phoen please take a look at https://github.com/K-Phoen/semver-release-action/pull/39 I tried to preserve your need to have label and the voices of the rest.
