### ISSUE TITLE
Add the ability to use action with an open PR. 

### ISSUE THREAD

**Issue by DontShaveTheYak** [K-Phoen/semver-release-action#37]
I have the use case where I want to do a "test" release.

I have `release_strategy` set to `none` but I still get. 

```
::Executing bumper guard ::debug release_branch=master,github_event_path=/github/workflow/event.json
pull request not closed::debug ::Guard returned a neutral code, stopping the execution.
```

**Comment by jeff-miller-cfa** [comment]
👍

**Comment by K-Phoen** [comment]
As explained in the README, this action explicitly limits its scope to semver bumps on merged PRs. I'd like to stick to this use-case :)
