### ISSUE TITLE
REPOSITORY IS INACTIVE AND AUTHOR UNRESPONSIVE

### ISSUE THREAD

**Issue by jmeridth** [K-Phoen/semver-release-action#49]
Have tried MULTIPLE times and submitted PR, no response.  Tried email directly.  No Response.

Best option is to fork and use your own.

Cheers.

**Comment by K-Phoen** [comment]
Nope, still alive :)

**Comment by jmeridth** [comment]
Motivated you to actually merge stuff 😄
